# Generated by Django 5.0.7 on 2024-09-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_delete_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idadmin', models.AutoField(db_column='idAdmin', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.AutoField(db_column='idEstudiante', primary_key=True, serialize=False)),
                ('tallacamisa', models.TextField(db_column='tallaCamisa')),
                ('institutoprocedencia', models.TextField(db_column='institutoProcedencia')),
                ('idmatricula', models.IntegerField(db_column='idMatricula')),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idprofesor', models.AutoField(db_column='idProfesor', primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('hojavida', models.FileField(max_length=512, upload_to='archivos/')),
                ('idarea', models.IntegerField(db_column='idArea')),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trimestres',
            fields=[
                ('idtrimestre', models.AutoField(db_column='idTrimestre', primary_key=True, serialize=False)),
                ('trimestre', models.TextField()),
                ('descripcion', models.TextField()),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
            ],
            options={
                'db_table': 'trimestres',
                'managed': False,
            },
        ),
    ]
