# Generated by Django 5.0.7 on 2024-08-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('idareas', models.AutoField(db_column='idAreas', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Areaslogros',
            fields=[
                ('idareaslogros', models.AutoField(db_column='idAreasLogros', primary_key=True, serialize=False)),
                ('resultado', models.TextField()),
                ('idareas', models.IntegerField(db_column='idAreas')),
                ('idlogros', models.IntegerField(db_column='idLogros')),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
            ],
            options={
                'db_table': 'areaslogros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('idinforme', models.AutoField(db_column='idInforme', primary_key=True, serialize=False)),
                ('nombreinforme', models.TextField(db_column='nombreInforme')),
                ('url', models.TextField()),
                ('fecha', models.DateField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
            ],
            options={
                'db_table': 'informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('idlogros', models.AutoField(db_column='idLogros', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('tipo', models.TextField()),
                ('comentario', models.TextField()),
            ],
            options={
                'db_table': 'logros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('idtrimestre', models.AutoField(db_column='idTrimestre', primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
                ('numero', models.TextField()),
            ],
            options={
                'db_table': 'trimestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('numerodocumento', models.TextField(db_column='numeroDocumento')),
                ('comuna', models.TextField(blank=True, null=True)),
                ('barrio', models.TextField()),
                ('correo', models.TextField()),
                ('urlimg', models.TextField(db_column='urlImg')),
                ('fecharegistro', models.DateField(db_column='fechaRegistro')),
                ('fechaingreso', models.DateField(db_column='fechaIngreso')),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('edad', models.TextField()),
                ('institutoprocedencia', models.TextField(blank=True, db_column='institutoProcedencia', null=True)),
                ('direccion', models.TextField()),
                ('idtipodocumento', models.IntegerField(db_column='idTipoDocumento')),
                ('idsexo', models.IntegerField(db_column='idSexo')),
                ('contrasena', models.TextField()),
                ('cambiocontrasena', models.TextField(db_column='cambioContrasena')),
                ('estado', models.TextField()),
                ('idrol', models.IntegerField(db_column='idRol')),
                ('idarea', models.TextField(db_column='idArea')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
