# Generated by Django 5.0.7 on 2024-09-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0002_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimestres',
            fields=[
                ('idtrimestre', models.AutoField(db_column='idTrimestre', primary_key=True, serialize=False)),
                ('trimestre', models.TextField()),
                ('descripcion', models.TextField()),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
            ],
            options={
                'db_table': 'trimestres',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Trimestre',
        ),
    ]
