# Generated by Django 5.0.7 on 2024-09-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0003_trimestres_delete_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idprofesor', models.AutoField(db_column='idProfesor', primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('hojavida', models.TextField(db_column='hojaVida')),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipologro',
            fields=[
                ('idtipologro', models.AutoField(db_column='idTipoLogro', primary_key=True, serialize=False)),
                ('tipologro', models.TextField(db_column='tipoLogro')),
            ],
            options={
                'db_table': 'tipologro',
                'managed': False,
            },
        ),
    ]
