# Generated by Django 5.0.7 on 2024-09-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0004_profesor_tipologro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.AutoField(db_column='idEstudiante', primary_key=True, serialize=False)),
                ('tallacamisa', models.TextField(db_column='tallaCamisa')),
                ('institutoprocedencia', models.TextField(db_column='institutoProcedencia')),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('idmatricula', models.IntegerField(db_column='idMatricula')),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
    ]
