# Generated by Django 5.0.7 on 2024-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0005_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logroestudiante',
            fields=[
                ('idlogroestudiante', models.AutoField(db_column='idLogroEstudiante', primary_key=True, serialize=False)),
                ('resultado', models.TextField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'logroestudiante',
                'managed': False,
            },
        ),
    ]
