# Generated by Django 5.0.7 on 2024-09-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0006_logroestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('idinforme', models.AutoField(db_column='idInforme', primary_key=True, serialize=False)),
                ('informe', models.TextField()),
                ('fecha', models.DateField()),
                ('observacion', models.TextField()),
            ],
            options={
                'db_table': 'informes',
                'managed': False,
            },
        ),
    ]
