# Generated by Django 5.0.7 on 2024-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('idareas', models.AutoField(db_column='idAreas', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('ideps', models.AutoField(db_column='idEps', primary_key=True, serialize=False)),
                ('nombreeps', models.TextField(db_column='nombreEps')),
            ],
            options={
                'db_table': 'eps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rh',
            fields=[
                ('idrh', models.AutoField(db_column='idRh', primary_key=True, serialize=False)),
                ('tiporh', models.TextField(db_column='tipoRh')),
            ],
            options={
                'db_table': 'rh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idsexo', models.AutoField(db_column='idSexo', primary_key=True, serialize=False)),
                ('sexo', models.TextField()),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('idtipodocumento', models.AutoField(db_column='idTipoDocumento', primary_key=True, serialize=False)),
                ('tipodocumento', models.TextField(db_column='tipoDocumento')),
            ],
            options={
                'db_table': 'tipodocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoparentesco',
            fields=[
                ('idparentesco', models.AutoField(db_column='idParentesco', primary_key=True, serialize=False)),
                ('parentesco', models.TextField()),
            ],
            options={
                'db_table': 'tipoparentesco',
                'managed': False,
            },
        ),
    ]
