# Generated by Django 5.0.7 on 2024-09-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0002_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(db_column='idDiagnostico', primary_key=True, serialize=False)),
                ('diagnostico', models.TextField()),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('iddiscapacidad', models.AutoField(db_column='idDiscapacidad', primary_key=True, serialize=False)),
                ('discapacidad', models.TextField()),
            ],
            options={
                'db_table': 'discapacidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('idmatricula', models.AutoField(db_column='idMatricula', primary_key=True, serialize=False)),
                ('matricula', models.TextField()),
            ],
            options={
                'db_table': 'matriculas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipologro',
            fields=[
                ('idtipologro', models.AutoField(db_column='idTipoLogro', primary_key=True, serialize=False)),
                ('tipologro', models.TextField(db_column='tipoLogro')),
            ],
            options={
                'db_table': 'tipologro',
                'managed': False,
            },
        ),
    ]
