# Generated by Django 5.0.7 on 2024-07-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('idareas', models.AutoField(db_column='idAreas', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Areaslogros',
            fields=[
                ('idareaslogros', models.AutoField(db_column='idAreasLogros', primary_key=True, serialize=False)),
                ('resultado', models.TextField()),
            ],
            options={
                'db_table': 'areaslogros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datosmedicos',
            fields=[
                ('iddatosmedicos', models.AutoField(db_column='idDatosMedicos', primary_key=True, serialize=False)),
                ('lugaratencion', models.TextField(db_column='lugarAtencion')),
                ('peso', models.TextField()),
                ('estatura', models.TextField()),
            ],
            options={
                'db_table': 'datosmedicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('ideps', models.AutoField(db_column='idEps', primary_key=True, serialize=False)),
                ('nombreeps', models.TextField(db_column='nombreEps')),
            ],
            options={
                'db_table': 'eps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiaclinica',
            fields=[
                ('idhistoriaclinica', models.AutoField(db_column='idHistoriaClinica', primary_key=True, serialize=False)),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField()),
                ('medicamentos', models.TextField()),
                ('cantidadmedicamentos', models.TextField(db_column='cantidadMedicamentos')),
                ('restriccionesalimenticias', models.TextField(db_column='restriccionesAlimenticias')),
                ('archivo', models.TextField()),
            ],
            options={
                'db_table': 'historiaclinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('idinforme', models.AutoField(db_column='idInforme', primary_key=True, serialize=False)),
                ('nombreinforme', models.TextField(db_column='nombreInforme')),
                ('url', models.TextField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('idlogros', models.AutoField(db_column='idLogros', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('tipo', models.TextField()),
                ('comentario', models.TextField()),
            ],
            options={
                'db_table': 'logros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('idpersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('numerodocumento', models.TextField(db_column='numeroDocumento')),
                ('comuna', models.TextField(blank=True, null=True)),
                ('barrio', models.TextField()),
                ('correo', models.TextField()),
                ('urlimg', models.TextField(db_column='urlImg')),
                ('fecharegistro', models.DateField(db_column='fechaRegistro')),
                ('fechaingreso', models.DateField(db_column='fechaIngreso')),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('edad', models.TextField()),
                ('institutoprocedencia', models.TextField(blank=True, db_column='institutoProcedencia', null=True)),
                ('direccion', models.TextField()),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('idresponsable', models.AutoField(db_column='idResponsable', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('correo', models.TextField()),
                ('numerodocumento', models.TextField(db_column='numeroDocumento')),
                ('telefono', models.TextField()),
                ('profesion', models.TextField()),
                ('ocupacion', models.TextField()),
                ('empresa', models.TextField()),
            ],
            options={
                'db_table': 'responsable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rh',
            fields=[
                ('idrh', models.AutoField(db_column='idRh', primary_key=True, serialize=False)),
                ('tiporh', models.TextField(db_column='tipoRh')),
            ],
            options={
                'db_table': 'rh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('rol', models.TextField()),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idsexo', models.AutoField(db_column='idSexo', primary_key=True, serialize=False)),
                ('sexo', models.TextField()),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('idtelefono', models.AutoField(db_column='idTelefono', primary_key=True, serialize=False)),
                ('numero', models.TextField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'telefono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('idtipodocumento', models.AutoField(db_column='idTipoDocumento', primary_key=True, serialize=False)),
                ('tipodocumento', models.TextField(db_column='tipoDocumento')),
            ],
            options={
                'db_table': 'tipodocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoparentesco',
            fields=[
                ('idparentesco', models.AutoField(db_column='idParentesco', primary_key=True, serialize=False)),
                ('parentesco', models.TextField()),
            ],
            options={
                'db_table': 'tipoparentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('contrasena', models.TextField()),
                ('cambiocontrasena', models.TextField(db_column='cambioContrasena')),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
