# Generated by Django 5.0.7 on 2024-07-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('numerodocumento', models.TextField(db_column='numeroDocumento')),
                ('comuna', models.TextField(blank=True, null=True)),
                ('barrio', models.TextField()),
                ('correo', models.TextField()),
                ('urlimg', models.TextField(db_column='urlImg')),
                ('fecharegistro', models.DateField(db_column='fechaRegistro')),
                ('fechaingreso', models.DateField(db_column='fechaIngreso')),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('edad', models.TextField()),
                ('institutoprocedencia', models.TextField(blank=True, db_column='institutoProcedencia', null=True)),
                ('direccion', models.TextField()),
                ('idtipodocumento', models.IntegerField(db_column='idTipoDocumento')),
                ('idsexo', models.IntegerField(db_column='idSexo')),
                ('contrasena', models.TextField()),
                ('cambiocontrasena', models.TextField(db_column='cambioContrasena')),
                ('estado', models.TextField()),
                ('idrol', models.IntegerField(db_column='idRol')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Personas',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
