# Generated by Django 5.0.7 on 2024-09-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_condicion_diagnostico_direccion_discapacidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idadmin', models.AutoField(db_column='idAdmin', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logroestudiante',
            fields=[
                ('idlogroestudiante', models.AutoField(db_column='idLogroEstudiante', primary_key=True, serialize=False)),
                ('resultado', models.TextField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'logroestudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('idlogro', models.AutoField(db_column='idLogro', primary_key=True, serialize=False)),
                ('logro', models.TextField()),
            ],
            options={
                'db_table': 'logros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipologro',
            fields=[
                ('idtipologro', models.AutoField(db_column='idTipoLogro', primary_key=True, serialize=False)),
                ('tipologro', models.TextField(db_column='tipoLogro')),
            ],
            options={
                'db_table': 'tipologro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trimestres',
            fields=[
                ('idtrimestre', models.AutoField(db_column='idTrimestre', primary_key=True, serialize=False)),
                ('trimestre', models.TextField()),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
            ],
            options={
                'db_table': 'trimestres',
                'managed': False,
            },
        ),
    ]
